### ISSUE TITLE
No text for empty invoices table

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-mail-settings#114]
Notice that when there are no payment methods available, we show a "You have no saved payment methods." text.

This doesn't happen on the invoices table which is right after the payment methods table:

![no text for 0 invoices](https://user-images.githubusercontent.com/44697797/63649792-73700180-c742-11e9-98de-997e16f7df8a.jpg)

There should be a placeholder text to indicate the empty state of the table, otherwise, it might look like a non-functional control.

**Comment by RandomAdversary** [comment]
Would be nice to have this for vpn-settings.
