### ISSUE TITLE
Payment modal doesn't open when arriving to upgrade screen from mailbox

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-mail-settings#115]
If you login with a free account to the mailbox, and click on the upgrade button in the toolbar, clicking on the `upgrade now` button in the upgrade modal won't work.

Instead of opening the payment modal, you'll get an `uncaught in promise` exception in the console.

**Steps to reproduce:**

1. Login with a free account to the mailbox
2. Click on the upgrade button in the top toolbar
3. In the upgrade modal in `/settings`, click on the `Upgrade Now` button
4. Notice nothing happens and you have an error in the console

* Interestingly, if you open the upgrade modal from within `/settings`, clicking on the `Upgrade Now` button works.

**Example:**

![payment failure when upgrading from mailbox](https://user-images.githubusercontent.com/44697797/63669046-3d319100-c7d9-11e9-91b6-4bc18805b848.gif)

**Comment by EpokK** [comment]
This should be fixed, it was an issue on Angular (v3 -> v4) project: The link was not correct.

**Comment by DaraQA** [comment]
The upgrade modal is not opened, it only flashes for a second
https://recordit.co/xVb2fCcdhk

**Comment by mmso** [comment]
It's fixed in the latest version which is not deployed yet

**Comment by DaraQA** [comment]
Still not fixed in the latest version
