### ISSUE TITLE
Target of  subnav links (right nav) 

### ISSUE THREAD

**Issue by nico3333fr** [ProtonMail/proton-mail-settings#121]
When I click on these links, the main page is positionned too low (probably due to sticky header).

![image](https://user-images.githubusercontent.com/2578321/64107310-75f1dd00-cd7a-11e9-853b-36f735faac54.png)

Solution: compute sticky header height and take it into account when scrolling.

**Comment by mmso** [comment]
That wouldn't solve it for the general case when you are refreshing the page with the #target-name set. Any idea how to fix that?

**Comment by nico3333fr** [comment]
Except detecting the fragment and scroll to the correct position, I don't have any idea :-\

**Comment by dhoko** [comment]
You can run on the 2sd frame (_1st one is browser ancher process_) a scrollTo with a padding.

ex: #target-name
```js
const offSetTop = x.querySelector(#target-name).offsetTop;
window.scrollTo(0, offSetTop + 60)
```

here the padding = 60px.
But it only works when you click or load the page. But it should be enough as the sidebar should not change the scroll when we match a section.

It can be done inside the sidebar as this is where we manage the click.

**Comment by nico3333fr** [comment]
Or maybe use `scrollIntoView` to do a smooth scrolling also.
