### ISSUE TITLE
Storage space editor rounds decimals to 0

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-mail-settings#122]
If you edit a sub-user account that is using a storage space of less than `1.5`, the editor is going to show the user as using `0.00 GB` of space.

**Example:**

![2019-09-04_11-51-28](https://user-images.githubusercontent.com/44697797/64273708-2cec8500-cf42-11e9-8345-7c0f10979e55.gif)

This is because the old v3 storage space editor allowed for decimals, while the new v4 always rounds to an exact value.

**The issue doesn't always happen in this way**. If you edit other user accounts with different (using non-standard storage values, like `6. 70 GB`), the value in the editor will be rounded to `1`:

![2019-09-04_18-34-58](https://user-images.githubusercontent.com/44697797/64273998-bc923380-cf42-11e9-8853-28abf5428cc7.gif)

**Comment by EpokK** [comment]
That's OK
