### ISSUE TITLE
2 year plans are available for ProtonMail

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/proton-mail-settings#124]
**Summary**
The 2 year plans are used during promotions, they shouldn't be available for all users.
This is probably a bug caused by adding 2 year plans for vpn.

**Steps to reproduce**
1. Go to /settings/subscription
2. Open the plans

**Screenshot**
![image](https://user-images.githubusercontent.com/11393457/64286148-32a39400-cf5d-11e9-8117-de59520eba93.png)

**Comment by EpokK** [comment]
This is expected and it's a new feature we want to have for v4.
