### ISSUE TITLE
The header text is hidden on 1366x768 resolution

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/proton-mail-settings#125]
**Steps to reproduce**
1. Go to inbox

**Current behavior**
![image](https://user-images.githubusercontent.com/11393457/64286503-e7d64c00-cf5d-11e9-9810-154fd99a75a0.png)

**Expected**
![image](https://user-images.githubusercontent.com/11393457/64286525-fae91c00-cf5d-11e9-8e8a-261977fe6f10.png)

**Related issue**
https://github.com/ProtonMail/proton-vpn-settings/issues/63

**Comment by nico3333fr** [comment]
Well, this is not that simple, see with "Update" link present for a free account
![image](https://user-images.githubusercontent.com/2578321/65751879-f0104a00-e10b-11e9-805c-1c49d36e66f3.png) (and we may have also another link for BF)

I'm at 1400px, and there is already not that much free space.  This is why I've hidden text at 1400.

**Comment by nico3333fr** [comment]
BTW, this is not related to Settings, but to Angular, I move it to the correct repo.

**Comment by nico3333fr** [comment]
Moved here https://github.com/ProtonMail/Angular/issues/9041
