### ISSUE TITLE
Bad contrast for settings icons on left sidebar with blue theme

### ISSUE THREAD

**Issue by econdepe** [ProtonMail/proton-mail-settings#132]
The icons on the left sidebar do not change color when changing themes. While the current color seems to be ok with dark and light theme, with the blue theme the contrast does not look great.

![image](https://user-images.githubusercontent.com/33841139/65500705-fd38f900-debf-11e9-897a-a123ab089e0f.png)

**Comment by nico3333fr** [comment]
I'll send a quick fix to avoid this case right now, but I've opened an issue on Design system for a more-pleasant solution: https://github.com/ProtonMail/design-system/issues/227 :)
