### ISSUE TITLE
Limited access warning isn't properly aligned

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-mail-settings#136]
The limited/restricted access error message that appears when a user class cannot view a certain page (or a free account browser for paid features) isn't aligned to the left side of the view.

**Example 1:**

![Screenshot_7](https://user-images.githubusercontent.com/44697797/65885042-2f53ca80-e39a-11e9-99b0-1147281e3b58.png)

**Example 2:**

![Screenshot_8](https://user-images.githubusercontent.com/44697797/65885083-4397c780-e39a-11e9-94b4-64619c66e289.png)

**Comment by EpokK** [comment]
The result you are seeing is expected. Design team will provide illustrations to fill the page.

**Comment by emnproton** [comment]
New design has been added.
