### ISSUE TITLE
Title attribute is missing

### ISSUE THREAD

**Issue by nikolanol** [ProtonMail/proton-mail-settings#139]
The menus in Settings are missing the page title attribute

![image](https://user-images.githubusercontent.com/49553343/66054620-95745500-e534-11e9-899b-c4e719287df0.png)

**Comment by nikolanol** [comment]
@Yiin Please update the title for `https://v4.protonmail.blue/settings` page as well

**Comment by dhoko** [comment]
There is a bug, on load it doens't set the title, the title only changes if we switch to another page
