### ISSUE TITLE
New payment method isn't shown after successful payment

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-mail-settings#162]
**Summary:**

If you pay for a ProtonMail subscription with a new card, after the transaction, the card will not be shown as a payment method.

The page needs a full refresh in order to load the new payment method in the payment methods section.

**Example:**

![ads8pYewpO](https://user-images.githubusercontent.com/44697797/67075130-d7cfa000-f18a-11e9-8e77-0cdbd45ea540.gif)

**Comment by EpokK** [comment]
To fix this issue, @N4M3Z needs to change the API to add an event for `PaymentMethods`.

**Comment by N4M3Z** [comment]
The relevant changes on the API side have been made available. Can this issue be closed?
