### ISSUE TITLE
Overlapping in Settings > Subscription > Plans/Invoices

### ISSUE THREAD

**Issue by matej-n** [ProtonMail/proton-mail-settings#165]
On smaller screens, there is an overlapping under the Subscription tab in Settings. 
The first issue is with the navigation bar on the right side which is going under/over the Plans table and Invoices table.
The second issue is with the blue My Subscription square and the names of the plans (ie Professional over Visionary etc).

![image](https://user-images.githubusercontent.com/31239087/67201671-0a85cc80-f407-11e9-8d68-7b11f358c62e.png)

**Comment by EpokK** [comment]
I'm closing this one since we plan to remove the right sidebar.
