### ISSUE TITLE
V4 extra polish - small bugs and UX fixes

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-mail-settings#172]
- [x] remove the blockquote (since we have the related settings section just under). This is my mistake.
![Capture d’écran 2019-10-22 à 10 45 32](https://user-images.githubusercontent.com/40168570/67271133-3d3ccd00-f4ba-11e9-82a2-168593b49815.png)

- [x] Number of addresses is wrong? Please double check the code
- [x] update the text in the blockquote to say : `Premium plans let you add multiple email addresses to your account. All the emails associated with them will appear in the same mailbox. If you are the admin of a Professional or Visionary plan, you can manage email addresses for each user in your organization. The email address at the top of the list will automatically be selected as the default email address.`
![Capture d’écran 2019-10-22 à 10 47 15](https://user-images.githubusercontent.com/40168570/67271362-a4f31800-f4ba-11e9-9933-e18f9019e909.png)

- [x] Stick label does not seem to have the processing animation integrated when transitioning from on to off (and back). Please double check.
![Capture d’écran 2019-10-22 à 10 49 24](https://user-images.githubusercontent.com/40168570/67271392-b3413400-f4ba-11e9-9420-28ccdb89eb2a.png)

- [x] Rename ProtonVPN apps to ProtonMail apps in the navigation bar on the right
![Capture d’écran 2019-10-22 à 10 52 35](https://user-images.githubusercontent.com/40168570/67274444-bb03d700-f4c0-11e9-935e-2c74968800e0.png)

**Comment by EpokK** [comment]
What I'm using:
``` jsx
{organization.UsedMembers} / {organization.MaxMembers}
{organization.UsedAddresses} / {organization.MaxAddresses}
```

**Comment by jovanjovanovski** [comment]
The main address and the @pm.me alias do not count towards these, so fi the screenshot shows all created aliases, it's correct (in this case 5/50)

**Comment by matstaz** [comment]
understood! thanks for clarifying @jovanjovanovski
