### ISSUE TITLE
Empty display name input box size

### ISSUE THREAD

**Issue by valentinbonneaud** [ProtonMail/proton-mail-settings#176]
If you have an empty display name the input box is very small!

It's fixed if I edit the display name and add one. The box display the name and has the correct size.

MacOS Catalina - Safari 13.0.2

![image](https://user-images.githubusercontent.com/1142481/67284027-13dd6a80-f4d5-11e9-8b36-49cd0de98081.png)

**Comment by valentinbonneaud** [comment]
Oh but now on v4 it is not allowed to have an empty Display Name? It was on v3?

**Comment by econdepe** [comment]
I think we should remove the impossibility of an empty Display Name. It will behave strangely for users that had an empty Display Name before v4. And also it's incompatible with the alert saying "leave each field empty for more privacy".

Also, the responsive behavior is not good on this page.

**Comment by valentinbonneaud** [comment]
I agree with @econdepe :)
