### ISSUE TITLE
V4 Responsive - Small UX improvements

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-mail-settings#179]
I noticed a couple of things while testing on my iPhone 7+
- [ ] can we increase the size of the label in the header. `settings` looks a little bit small compared to the icons
- [x] is it possible to keep the header fixed as the user scrolls down the page?
- [x] when I tap on a settings option in the left hand navigation menu, the menu does not close automatically. I need to press the X to close it and see the content of that page. I would be great if the menu could close, like what we do with Mailbox.

**Comment by matstaz** [comment]
the header is indeed fixed. After talking to Aurélien, it seems to be a safari problem when the content on the page does not extend beyond the screen view.

**Comment by matstaz** [comment]
I added another point above. When I tap on a settings page in the left hand navigation menu, the menu does not close automatically. I need to press the X to close it and see the content of that page.

**Comment by emnproton** [comment]
Verified as fixed.
