### ISSUE TITLE
Settings title label is cut-off on mobile devices

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-mail-settings#181]
**Summary:**

The top `Settings` label has its bottom part cut-off on mobile devices. The same issue doesn't happen with the `Contacts` label in the contacts app.

**Example:**

![Screenshot_14](https://user-images.githubusercontent.com/44697797/67461036-b2d0a680-f63c-11e9-9ef3-48f72783aaa3.png)

**Env:**

Tested on iPhone XR iOS 13 and Chrome desktop set in mobile device mode.

**Comment by nico3333fr** [comment]
Is the bug still present?

I can't reproduce even on my mobile (the line-height is at 1.5, which is enough for not having the text cut off)
![image](https://user-images.githubusercontent.com/2578321/67585596-2adbc100-f750-11e9-8dea-e5e20aadadef.png)
