### ISSUE TITLE
2FA successful login is showed as invalid login in authentication logs

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-mail-settings#185]
If you login successfully with your 2FA code, the log will be shown as `login failure (2FA)` in the authentication logs page.

**v3:**

![image](https://user-images.githubusercontent.com/44697797/67488302-dfea7c80-f66f-11e9-96b0-2f68c2ff6832.png)

**v4 (same logs):**

![image](https://user-images.githubusercontent.com/44697797/67488318-e4af3080-f66f-11e9-8b23-eb7242df46db.png)

**Comment by EpokK** [comment]
Fixed in a206a0c

**Comment by emnproton** [comment]
Verified as fixed.
