### ISSUE TITLE
Popup when changing your theme will remove an existing custom theme

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/proton-mail-settings#186]
**Is your feature request related to a problem? Please describe.**

On v4, if you have a custom theme and want to change to the default theme, your customizations will be removed. There is a warning saying that, but I think we could add a popup asking for confirmation if your custom theme is not empty.

My custom theme was causing some issues on the v4 design so I wanted to switch to the default one to try the new design and I lost all my customizations :( IMO with this card design you expect your customizations to stay, it's just selecting another theme. It's not like on v3 where you had to click on `Reset Theme`.

![image](https://user-images.githubusercontent.com/1142481/67489597-1de8a000-f672-11e9-8977-68d7c8d47a1f.png)

**Comment by emnproton** [comment]
Verified as fixed.
