### ISSUE TITLE
Require exact match toggle has opposite functionality in v3

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-mail-settings#191]
**Summary:**

CS Report: https://proton.atlassian.net/browse/CLIENT-1711

The `Do not require exact match` toggle label has been changed in v4 to say `Require exact match`.

This seems to be an error, as the toggle works the same way in v3 as it does on v4. So disabling exact match on v4 actually enabled exact match on v3.

We need to change the label on the toggle in v4 to say  `Do not require exact match` 

**v3:**

![image](https://user-images.githubusercontent.com/44697797/67562504-1c28e600-f71f-11e9-91fc-7de410ca6c53.png)

**v4:**

![image](https://user-images.githubusercontent.com/44697797/67562480-16330500-f71f-11e9-90c8-315d9f700950.png)

**Comment by EpokK** [comment]
@mmso check the validity of the sentence with @matstaz before to start on it please.

**Comment by matstaz** [comment]
We updated the string of text to positive rather than negative. Because there is less thinking and we avoid double negation.

Require exact match > yes > I know that only exact matches will be returned
Require exact match > no > I know that anything can be returned

In my test, it seems like the feature does not work. Regardless of on or off, I get the same results.

**Comment by matstaz** [comment]
So the righ behavior is:

Required exact match OFF > user gets all results that include the string
Required exact match ON > user only gets words that matches

**Comment by emnproton** [comment]
Basically, when we enable the toggle on v4, we need to disable it on v3. So I guess setting to `Enabled` on v4 needs to set the value to `false` in order to not break v3.

**Comment by matstaz** [comment]
V3 seems to also be broken btw. We get the same results regardless of whether require exact match is on or off

**Comment by emnproton** [comment]
Verified as fixed.
