### ISSUE TITLE
`Attach screenshot` button does not appear properly in French

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-mail-settings#192]
**Summary:**

CS Report: https://proton.atlassian.net/browse/CLIENT-1717

When the PM settings is set to French, the `attach screenshot` button is not properly displayed.

**Screenshot:**

![image](https://user-images.githubusercontent.com/44697797/67569281-c0665900-f72e-11e9-9574-f3652fdcf713.png)

**Comment by emnproton** [comment]
Issue is still occurring when opening the bug report modal while app is set to French.

**Comment by EpokK** [comment]
This issue should be reported to localization team, I explicitely mentioned that in the context translation for translators.
