### ISSUE TITLE
Signature 'not set' placeholder text is not properly aligned

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-mail-settings#194]
**Summary:**

CS Report: https://proton.atlassian.net/browse/CLIENT-1722

If you log in to an account that has never had a signature set, the `not set` placeholder text in the signature area will not be properly aligned.

**Screenshot:**

![image](https://user-images.githubusercontent.com/44697797/67571634-c4957500-f734-11e9-8848-9bcbec92c060.png)

**Comment by marisusis** [comment]
I'll give this a shot

**Comment by emnproton** [comment]
Verified as fixed.
