### ISSUE TITLE
V4 beta polish - Subscription quick fixes

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-mail-settings#196]
- [x] Current selected plan can say `update` but other plans should say `select`

![Capture d’écran 2019-10-25 à 15 43 31](https://user-images.githubusercontent.com/40168570/67576277-8d2bc600-f73e-11e9-9672-94931ae39193.png)

- [x] Update button should be consistent (and white) in my opinion
![Capture d’écran 2019-10-25 à 15 43 39](https://user-images.githubusercontent.com/40168570/67576371-bb110a80-f73e-11e9-8a78-47ca827869f1.png)

- [x] tooltips should be on same row if pssible
![Capture d’écran 2019-10-25 à 15 43 59](https://user-images.githubusercontent.com/40168570/67576417-ccf2ad80-f73e-11e9-9558-54a22a752ef3.png)

- [x] don't we have a new payment form that had more width so security code placeholder text fits in?
![Capture d’écran 2019-10-25 à 15 44 36](https://user-images.githubusercontent.com/40168570/67576465-e1cf4100-f73e-11e9-833e-657533c6f6c6.png)

- [x] `Add VPN`/ `Edit VPN`sould take the user to the VPN protection screen directly. It currently takes the user to the customization screen
- [x] do not auto-select **VPNPLus** when user clicks on `Add VPN`. We let the user make the selection.

**Comment by nikolanol** [comment]
Tooltips are removed when selecting a Plus plan, but if you select Professional you can still see the tooltips under the dropdown menus. 
Also we should place the tooltip icon in the same row next to 'IMAP / SMTP support'

![image](https://user-images.githubusercontent.com/49553343/68202631-5ec2ac00-ffc4-11e9-82ab-f8f649698d20.png)

**Comment by EpokK** [comment]
Pushed a fix for it.
