### ISSUE TITLE
Capitalization mismatch when the display name starts with a capital letter

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-mail-settings#199]
**Summary:**

CS Report: https://proton.atlassian.net/browse/CLIENT-1731

If you enter a display name with multiple names, the settings and contacts app will capitalize all the first letters in all the words.

This is an issue because, in some languages, middle names aren't supposed to be capitalized.

---

Example of how my display name is shown in mailbox vs settings:

**Mailbox:**

![image](https://user-images.githubusercontent.com/44697797/67658949-672f3d00-f95b-11e9-86ae-a4e5c9207876.png)

**Settings:**

![image](https://user-images.githubusercontent.com/44697797/67658945-61395c00-f95b-11e9-82bc-0790dd10c6a7.png)

We need the logic from the mailbox, applied to settings/contacts.

**Comment by nico3333fr** [comment]
This has been fixed (fix available on blue) when we harmonized the dropdown classes.
