### ISSUE TITLE
Visionary Plan is shown with 30GB of storage capacity instead of the 20GB available

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-mail-settings#200]
**CS Report**: https://proton.atlassian.net/browse/CLIENT-1739

On V4 beta, Settings > Subscription, the Visionary plan is shown with 30GB of storage capacity instead of the 20GB available.

**Screenshot:**

![image](https://user-images.githubusercontent.com/44697797/67661112-a8761b80-f960-11e9-9c6c-d80eb1d21c68.png)

**Comment by EpokK** [comment]
Already fixed
