### ISSUE TITLE
"Preview invoice" function doesn't output anything

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-mail-settings#201]
**Description**

CS Report: https://proton.atlassian.net/browse/CLIENT-1742

This was tested on up to date versions for Chrome and Firefox, with JavaScript enabled. 

**Steps to reproduce:**

1. Login to V4 and navigate to Settings> Subscription.
2. Scroll down to the Invoices section and click on "View" next to an invoice.
3. Get the result: Blank preview invoice

**Screenshot:**

![image](https://user-images.githubusercontent.com/44697797/67661245-fc810000-f960-11e9-8a59-11e93095f9de.png)

**Comment by EpokK** [comment]
```
Refused to load plugin data from 'blob:https://beta.protonmail.com/8405846c-84eb-449d-8d83-ebb14d19cc60' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'object-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**Comment by EpokK** [comment]
@bartbutler deployed the CSP fix on beta servers.

**Comment by emnproton** [comment]
Verified as fixed.
