### ISSUE TITLE
Can't add additional addresses to specific test account

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-mail-settings#205]
There is a specific test account that is missing the `Add Address` button.

CS Issue: https://proton.atlassian.net/browse/CLIENT-1746

**Screenshot:**

![image](https://user-images.githubusercontent.com/44697797/67675162-c18dc500-f97e-11e9-971b-b2af7ad9b5a9.png)

Please contact for login info.

**Comment by matstaz** [comment]
@EpokK what shall we ask the customer for? Seems strange.

**Comment by emnproton** [comment]
I already have the login info (it's an internal test account).

**Comment by emnproton** [comment]
Verified as fixed.
