### ISSUE TITLE
When trying to activate pm.me on visionary an error pops up

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-mail-settings#206]
> free premium address must be created using setup

<img width="1387" alt="Screenshot 2019-10-25 at 15 29 50" src="https://user-images.githubusercontent.com/40168570/67680119-eab45280-f98a-11e9-8392-59c763109afc.png">

**Comment by matstaz** [comment]
Check with @Anirim for more info in case this is to obvious

**Comment by EpokK** [comment]
The user needs to activate `@pm.me` on his account first as we do on v3:

<img width="893" alt="Address creation" src="https://user-images.githubusercontent.com/1345786/67715328-ed826800-f9c9-11e9-9b79-bc1463475ee0.png">
<img width="684" alt="Activation" src="https://user-images.githubusercontent.com/1345786/67715225-b01dda80-f9c9-11e9-8fcb-3d0bfc1da8d3.png">

But we don't have this part in v4.
