### ISSUE TITLE
When user is subscribed to both VPN and Mail, settings overview does not show the right image (invite user to beta)

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-mail-settings#207]
See Screenshot. Visionary is correct though.

![Capture d’écran 2019-10-28 à 14 03 48](https://user-images.githubusercontent.com/40168570/67680663-f5bbb280-f98b-11e9-90e5-c9ad6e3091fc.png)

**Comment by emnproton** [comment]
Verified as fixed.
