### ISSUE TITLE
Clicking on the label of a toggle takes action V4 Beta feedback

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-mail-settings#208]
When I click on the label or accidentally think I need to click on the tootlip icon, the toggle switches on/off.

Only the toggle should be actionable by the user, not the label

**Comment by Swiip** [comment]
This request is quite in opposition of the standard behavior of the browsers and therefore can reduce the accessibility. Ping @nico3333fr.

Options:
- Break the link between the label and the toggle but it's bad for a11n
- Artificially prevent the click on the label to be transmitted to the toggle, a bit more difficult, still bad for accessibility, perhaps less
- Something else?

So I'm not sure how to handle it.

**Comment by matstaz** [comment]
Never mind. Keep the behavior as is!
