### ISSUE TITLE
Incorrect plural form in some buttons

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-mail-settings#216]
**Summary:**

There are a few buttons (in the `related settings` section) that use an incorrect plural form.

**Example:**

- [ ] `Domains settings` should be `Domain settings`. `Users settings` should be `User settings`

These buttons are found in the Organization, Custom domains and Address sections.

![image](https://user-images.githubusercontent.com/44697797/67848902-d8aaef00-fb05-11e9-8fd9-91b3612b0d0b.png)

---

- [ ]  `Addresses settings` should be `Address settings` in the Custom Domains section

![image](https://user-images.githubusercontent.com/44697797/67849087-2f182d80-fb06-11e9-93fa-07038254f986.png)

**Comment by luckymurari** [comment]
Hi I would like to work on this

**Comment by emnproton** [comment]
Verified as fixed.
