### ISSUE TITLE
Improvements to the filter modal

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-mail-settings#218]
- [ ] the Trash icon should not be shown when there is only 1 condition
- [ ] the action to move to `Spam` and `trash` are missing from the dropdown
- [ ] the move to `mailbox`should say move to `inbox`
- [ ] the action to send auto-reply is missing
- [ ] For the labels, I thought we want wanted to create this new component that has both a dropown selector and an auto-complete capability. I can either type in or click on the drop down to view the list.

<img width="703" alt="Capture d’écran 2019-10-31 à 09 49 13" src="https://user-images.githubusercontent.com/40168570/67932361-0fdfd580-fbc4-11e9-8686-f7a98240c9e6.png">
<img width="326" alt="Capture d’écran 2019-10-31 à 09 47 53" src="https://user-images.githubusercontent.com/40168570/67932386-1b330100-fbc4-11e9-971a-05042e25bcc1.png">

**Comment by Swiip** [comment]
Sent a PR about this, it looks like this:

![Capture d’écran 2019-11-01 à 14 32 04](https://user-images.githubusercontent.com/475895/68028504-5d883b00-fcb5-11e9-8849-6fc9d4a4a830.png)

About the dropdown + autocomplete component. It doesn't exist yet, I'll check with @EpokK if I commit to work on adding one.
