### ISSUE TITLE
UK ZIP codes which contain blank spaces are not accepted as a payment method

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-mail-settings#227]
**Summary:**

One user has reported that ZIP codes with the format "AAN NAA" are not accepted because of the blank space.

Some countries (like the UK) have zip codes that have blank spaces in between and they should be accepted since it is the correct format and the user is misled that they have entered the wrong ZIP code.

**Example:**

![CgZxiEpZgt](https://user-images.githubusercontent.com/44697797/68118815-3b82f880-ff01-11e9-9c91-0049a910c02b.gif)

CS Report: https://proton.atlassian.net/browse/CLIENT-1795

**Comment by N4M3Z** [comment]
Being addressed on the API side, deploy this week.
