### ISSUE TITLE
Key generation on private users is still in v3 style

### ISSUE THREAD

**Issue by jovanjovanovski** [ProtonMail/proton-mail-settings#235]
The modal for generting keys for new addresses is shown in the old style.

Steps to reproduce:
1. Log in on `dec@protonteams.com`/`123`
2. See the modal for keys generation

![Screen Shot 2019-11-11 at 14 56 35](https://user-images.githubusercontent.com/16116122/68592549-a39e8500-0493-11ea-9d35-29c7da11bf2b.png)

**Comment by mmso** [comment]
Could you please move this issue to https://github.com/ProtonMail/Angular/issues and tag it with v4 @jovanjovanovski ?

**Comment by mmso** [comment]
Moved here https://github.com/ProtonMail/Angular/issues/9293
