### ISSUE TITLE
V4 Beta Feedback - multiple issues with filter modal

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-mail-settings#236]
- [x] When I have more than 1 condition, and I try to delete any condition (except the last one), it is always the last condition that gets removed. The expected behavior is to have the one trash be removed.

- [x]  "You must choose a type of condition" error is misaligned"
- [x] "A filter must have an action" error is misaligned

<img width="703" alt="Capture d’écran 2019-11-11 à 15 37 09" src="https://user-images.githubusercontent.com/40168570/68595347-908eb380-0499-11ea-932b-3b96aabe40e3.png">

<img width="703" alt="Capture d’écran 2019-11-11 à 15 33 06" src="https://user-images.githubusercontent.com/40168570/68595338-8bc9ff80-0499-11ea-8e71-3f34fb0ace12.png">

- [ ] Errors in the form do not get cleared after I correct my input.
<img width="705" alt="Capture d’écran 2019-11-11 à 15 32 59" src="https://user-images.githubusercontent.com/40168570/68595389-a69c7400-0499-11ea-816a-b8887ad10be7.png">

- [x] When I try to save a filter, nothing happens. I keep getting an error around the value field despite having provided a value.

**Comment by Swiip** [comment]
About the last point, it's both "normal" and very annoying. As it is right now, a value is considered present only if you use the Add button. In the screenshot, the form considered that you didn't validated the value.

@matstaz Do you want me to change the current behavior to handle the current value input as a valid input?
