### ISSUE TITLE
Can't toggle auto load remote and auto load embedded images at the same time

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-mail-settings#242]
**Summary:**

CS Report: https://proton.atlassian.net/browse/CLIENT-1846

If you enable or disable two toggles at the same time, only one toggle is going to have it's state switched.

**Example:**

![kYfJE8WZk1](https://user-images.githubusercontent.com/44697797/68858607-adb7c200-06e5-11ea-9c47-b591bf5d11e1.gif)

**Comment by matstaz** [comment]
do you agree it is somewhat of an edge case?
