### ISSUE TITLE
Push notifications for android client 

### ISSUE THREAD

**Issue by jhoc2000** [ProtonMail/proton-mail-settings#244]
The developers of ProtonMail must be commended for providing a secure email service in these days when social media and big internet companies are harvesting users information for manipulation of the masses. I expect that most people who use ProtonMail are concerned about their privacy and try to avoid the harvesting of his or her data. For privacy reasons I disable many of the google apps on my android smartphone such as Google Play Store, Google Play Services, Google Services Framework, etcetera. Unfortunately ProtonMail relies on Google services for push notifications and therefore I am not notified when emails arrive in my account.

Could the developers please provide a push notifications method in the next version that is not reliant on Google Services? Kontalk provides end-to-end encryption messenging and is open source that is not relient on Google for push notifications. Surely the push notifications component of that code could be used in ProtonMail to provide even more privacy to its users.

I look forward to the next, more useful version.

**Comment by EpokK** [comment]
Not the proper place to report this issue.

**Comment by jhoc2000** [comment]
Where is "the proper place to report this issue"?

**Comment by EpokK** [comment]
Here, it's the public Github repository for ProtonMail settings in React (web-app). So you should report your issue to our [customer support](https://protonmail.com/support-form) please.
