### ISSUE TITLE
BF modal

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/proton-mail-settings#248]
![BF1](https://user-images.githubusercontent.com/1345786/69352263-e8d56a80-0c7c-11ea-92f0-921f003c5eff.png)

- [x] The price for the bundle should be 7.50 instead 7.5
- [x] The text in the footer is not the same in v4 as in v3
- [x] The text under "Get the deal" should be Billed as 39.99 € for one year (1) (and in  (2), (3) - for two years)

**Comment by nikolanol** [comment]
Expected, v3:  
![image](https://user-images.githubusercontent.com/49553343/69352617-8335ae00-0c7d-11ea-8bb2-307f13f0a8c2.png)

**Comment by EpokK** [comment]
> The text in the footer is not the same in v4 as in v3

Footer text is correct [cf](https://protonvpn.com/blackfriday)

> The text under "Get the deal" should be Billed as 39.99 € for one year (1) (and in (2), (3) - for two years)

We already precise the billing cycle at the top of the plan.

**Comment by d310n9** [comment]
@EpokK @nikolanol 

- richard is right, we do not need the specification of "for one year"/"for two years"
- have updated wireframes and attaching here
- i'll request appropriate changes on v3 as well
[bf2019_webapp_modals_mail.pdf](https://github.com/ProtonMail/proton-mail-settings/files/3876317/bf2019_webapp_modals_mail.pdf)

**Comment by d310n9** [comment]
@EpokK 

- [ ] note updated footer text changes plz (as per wireframes above and current whats live on landing pages) 

pasting here for easy reference 
```
    (1) Renews after 1 year at a discounted annual price of 48 € per year (20% discount)
    (2) Renews after 2 years at a discounted 2-year price of 79 € every 2 years (33% discount)
    (3) Renews after 2 years at a discounted 2-year & bundle price of 190.40 € every 2 years (47% discount)
```
