### ISSUE TITLE
PVPN subscription not show in Order summary when upgrading to Mail Plus

### ISSUE THREAD

**Issue by Dara-QA** [ProtonMail/proton-mail-settings#254]
1. Make 2y subscription on PVPN (Mail free/ PVPN Plus)
2. Make a subscription on Mail Plus (2y)
3. On the 'Order summary' is shown as is I don't have a ProtonVPN subscription. The amount paid for PVPN is prorated

If you need such account, write me on slack

**Comment by EpokK** [comment]
From what I'm seeing, it's expected: if you click on **SELECT**, you are choosing a config without ProtonVPN. A new subscription flow is coming soon, it will make the process more clear.
