### ISSUE TITLE
Beta feedback - When trying to delete one of the non-primary keys of an address there is no option to decline exporting the key

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/proton-mail-settings#255]
Report in JIRA here: https://proton.atlassian.net/browse/CLIENT-1893

When trying to delete one of the non-primary keys from https://beta.protonmail.com/settings/keys, there is no option to decline exporting the private key in question. At the second warning message, the user is only presented with the options Cancel (which cancels the whole process) and Yes (which will continue the process).

In V3, you are presented with the options Cancel (which continues the process but doesn't export the key) and Export (which exports the key).

- [ ] Suggestion: Add an option to decline exporting the key but continuing the process by adding a No button. The cancel button should remain and should cancel the whole process as it does at the moment.

- [ ] Other suggestion: Another thing regarding the key deletion process: in the very last step after the key has been exported and deleted, the modal has a Cancel button. There’s nothing to cancel there and the button should be removed.

**Comment by mmso** [comment]
Duplicate of https://github.com/ProtonMail/proton-mail-settings/issues/101

**Comment by matstaz** [comment]
closing. Transferred comments to the other issues.
