### ISSUE TITLE
Navigation bar disapear

### ISSUE THREAD

**Issue by valentinbonneaud** [ProtonMail/proton-mail-settings#269]
If you scroll, the navigation bar scroll as well. In the screenshot bellow, the bar completelly disapeared!

![image](https://user-images.githubusercontent.com/1142481/70795810-f627d580-1da0-11ea-8a6b-b9c424afd9e1.png)

On Safari 13.0.3 / MacOS Catalina

**Comment by EpokK** [comment]
We plan to revamp the [sub sidebar](https://github.com/ProtonMail/proton-mail-settings/issues/258)
